CREATE DATABASE JOB_RECOMMENDATION
USE JOB_RECOMMENDATION

CREATE TABLE BAIDANG (
	MaBaiDang INT IDENTITY (1,1),
	MaCongTy INT,
	TenCongViec NVARCHAR(MAX),
	MoTa NVARCHAR(MAX),
	LuongMin INT,
	LuongMax INT,
	ThamNien INT,
	WebsiteBaiGoc NVARCHAR(MAX),
	-- Cap bac ?? --
	NgayDangBai DateTime,
	GhiChu NVARCHAR(MAX),
	MaTaiKhoan INT,

	CONSTRAINT BAIDANG_PK PRIMARY KEY (MaBaiDang)
)

CREATE TABLE HOSOCONGTY (
	MaCongTy INT IDENTITY (1,1),
	TenCongTy NVARCHAR(MAX),
	Website NVARCHAR(MAX),
	DiaChi NVARCHAR(MAX),
	QuocTich NVARCHAR(MAX),
	CheDoDaiNgo NVARCHAR(MAX),
	MoTaThem NVARCHAR(MAX),
	AnhCongTy VARBINARY(MAX)

	CONSTRAINT HOSOCONGTY_PK PRIMARY KEY (MaCongTy)
)

CREATE TABLE UNGVIEN (
	MaUngVien INT IDENTITY (1,1),
	Ten NVARCHAR(MAX),
	Tuoi INT,
	DiaChi NVARCHAR(MAX),
	Email NVARCHAR(MAX),
	SDT NVARCHAR(MAX),
	ThamNien INT,

	CONSTRAINT UNGVIEN_PK PRIMARY KEY (MaUngVien)
)

CREATE TABLE KINANG (
	MaKiNang INT IDENTITY (1,1),
	TenKiNang NVARCHAR(MAX),

	CONSTRAINT KINANG_PK PRIMARY KEY (MaKiNang)
)

CREATE TABLE KINANG_UNGVIEN (
	MaUngVien INT,
	MaKiNang INT

	CONSTRAINT KINANG_UNGVIEN_PK PRIMARY KEY (MaKiNang, MaUngVien)
)

CREATE TABLE KINANG_BAIDANG (
	MaBaiDang INT,
	MaKiNang INT,

	CONSTRAINT KINANG_BAIDANG_PK PRIMARY KEY (MaKiNang, MaBaiDang)
)

CREATE TABLE CV (
	MaCV INT IDENTITY (1,1),
	MaUngVien INT,
	AnhCV VARBINARY(MAX),

	CONSTRAINT CV_PK PRIMARY KEY (MaCV)
)

CREATE TABLE UNGTUYEN (
	MaUngVien INT,
	MaBaiDang INT,
	NgayUngTuyen DateTime,
	ChapThuan BIT -- Ung vien duoc ung tuyen co dc dau hay k --

	CONSTRAINT UNGTUYEN_PK PRIMARY KEY (MaUngVien, MaBaiDang)
)

CREATE TABLE PHIEUTOCAO (
	MaPhieuToCao INT IDENTITY (1,1),
	MaBaiDang INT,
	LyDo NVARCHAR(MAX),
	ThoiGian DateTime,
	MoTa NVARCHAR(MAX)

	CONSTRAINT PHIEUTOCAO_PK PRIMARY KEY (MaPhieuToCao)
)

CREATE TABLE PHIEUPHAT (
	MaPhieuPhat INT IDENTITY (1,1),
	MaPhieuToCao INT,
	MaTaiKhoan INT,
	SoTienPhat INT,
	ThoiGian DateTime,
	MoTa NVARCHAR(MAX)

	CONSTRAINT PHIEUPHAT_PK PRIMARY KEY (MaPhieuPhat)
)

CREATE TABLE TAIKHOAN (
	MaTaiKhoan INT IDENTITY (1,1),
	TenDangNhap VARCHAR(MAX),
	MatKhau VARCHAR(MAX),
	MaChucVu INT,
	MaNhanVien INT,

	CONSTRAINT TAIKHOAN_PK PRIMARY KEY (MaTaiKhoan)
)

CREATE TABLE NHANVIEN (
	MaNhanVien INT IDENTITY (1,1),
	TenNhanVien NVARCHAR(MAX),
	Tuoi INT,
	SDT VARCHAR(10),
	Email VARCHAR(MAX)

	CONSTRAINT NHANVIEN_PK PRIMARY KEY (MaNhanVien)
)

CREATE TABLE CHUCVU (
	MaChucVu INT IDENTITY (1,1),
	TenChucVu NVARCHAR(MAX),
	
	CONSTRAINT CHUCVU_PK PRIMARY KEY (MaChucVu)
)

CREATE TABLE LICHSULAMVIEC (
	MaLSLV INT IDENTITY (1,1),
	MaTaiKhoan INT,
	CaLamViec NVARCHAR(MAX),
	NgayLamViec DATETIME,

	CONSTRAINT LICHSULAMVIEC_PK PRIMARY KEY (MaLSLV)
)

CREATE TABLE CHITIETLAMVIEC (
	MaLSLV INT,
	MaBaiDang INT

	CONSTRAINT CHITIETLAMVIEC_PK PRIMARY KEY (MaLSLV, MaBaiDang)
)

CREATE TABLE THONGKE (
	MaThongKe INT IDENTITY (1,1),
	ThoiGian DATETIME, --Thang va Nam--
	SoBaiDangDaThem INT,
	SoCVDaThem INT,
	SoNguoiDaUngTuyen INT

	CONSTRAINT THONGKE_PK PRIMARY KEY (MaThongKe)
)

CREATE TABLE TONGTHONGKE (
	MaTongTK INT IDENTITY (1,1),
	TongBaiDang INT,
	TongCV INT,
	TongNguoiDaUngTuyen INT,

	CONSTRAINT TONGTHONGKE_PK PRIMARY KEY (MaTongTK)
)

ALTER TABLE BAIDANG ADD CONSTRAINT FK_MaCongTy_BD FOREIGN KEY (MaCongTy) REFERENCES HOSOCONGTY(MaCongTy)
ALTER TABLE BAIDANG ADD CONSTRAINT FK_MaTaiKhoan_BD FOREIGN KEY (MaTaiKhoan) REFERENCES TAIKHOAN(MaTaiKhoan)

ALTER TABLE KINANG_UNGVIEN ADD CONSTRAINT FK_MaUngVien_KNUV FOREIGN KEY (MaUngVien) REFERENCES UNGVIEN(MaUngVien)
ALTER TABLE KINANG_UNGVIEN ADD CONSTRAINT FK_MaKiNang_KNUV FOREIGN KEY (MaKiNang) REFERENCES KINANG(MaKiNang)

ALTER TABLE KINANG_BAIDANG ADD CONSTRAINT FK_MaKiNang_KNBD FOREIGN KEY (MaKiNang) REFERENCES KINANG(MaKiNang)
ALTER TABLE KINANG_BAIDANG ADD CONSTRAINT FK_MaBaiDang_KNBD FOREIGN KEY (MaBaiDang) REFERENCES BAIDANG(MaBaiDang)

ALTER TABLE CV ADD CONSTRAINT FK_MaUngVien_CV FOREIGN KEY (MaUngVien) REFERENCES UNGVIEN(MaUngVien)

ALTER TABLE UNGTUYEN ADD CONSTRAINT FK_MaUngVien_UT FOREIGN KEY (MaUngVien) REFERENCES UNGVIEN(MaUngVien)
ALTER TABLE UNGTUYEN ADD CONSTRAINT FK_MaBaiDang_UT FOREIGN KEY (MaBaiDang) REFERENCES BAIDANG(MaBaiDang)

ALTER TABLE PHIEUTOCAO ADD CONSTRAINT FK_MaBaiDang_PTC FOREIGN KEY (MaBaiDang) REFERENCES BAIDANG(MaBaiDang)

ALTER TABLE PHIEUPHAT ADD CONSTRAINT FK_MaPhieuToCao_PP FOREIGN KEY (MaPhieuToCao) REFERENCES PHIEUTOCAO(MaPhieuToCao)
ALTER TABLE PHIEUPHAT ADD CONSTRAINT FK_MaTaiKhoan_PP FOREIGN KEY (MaTaiKhoan) REFERENCES TAIKHOAN(MaTaiKhoan)

ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_ChucVu_TK FOREIGN KEY (ChucVu) REFERENCES CHUCVU(MaChucVu)
ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_MaNhanVien_TK FOREIGN KEY (ChucVu) REFERENCES NHANVIEN(MaNhanVien)

ALTER TABLE LICHSULAMVIEC ADD CONSTRAINT FK_MaTaiKhoan_LSLV FOREIGN KEY (MaTaiKhoan) REFERENCES TAIKHOAN(MaTaiKhoan)

ALTER TABLE CHITIETLAMVIEC ADD CONSTRAINT FK_MaLSLV_CTLV FOREIGN KEY (MaLSLV) REFERENCES LICHSULAMVIEC(MaLSLV)
ALTER TABLE CHITIETLAMVIEC ADD CONSTRAINT FK_MaBaiDang_CTLV FOREIGN KEY (MaBaiDang) REFERENCES BAIDANG(MaBaiDang)


INSERT INTO KINANG(TenKiNang) VALUES ('Front-End')
INSERT INTO KINANG(TenKiNang) VALUES ('Back-End')
INSERT INTO KINANG(TenKiNang) VALUES ('Fullstack')














































